name: Windows Release

on:
  push:
    branches:
      - 'main'

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   5.15.2
  ARTIFACT:     qt-planets-build.zip

jobs:
  build:
    runs-on:  windows-2019

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: (2) Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}
        run: |
          git fetch --all --tags -f
#      - name: (3) Install Qt
#        uses: jurplel/install-qt-action@v2
#        with:
#          version:      ${{ env.QT_VERSION }}
#          host:         windows
#          target:       desktop
#          arch:         win64_msvc2019_64
#          dir:          ${{ runner.temp }}
#          modules:      qtcharts qt3d
#          setup-python: false
              
      - name: (6) Create build directory
        run:  mkdir ${{ runner.temp }}\build

      - name: (7) Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
 
      - name: Cache Build
        uses: actions/cache@v3
        with: 
          path: ${{ runner.temp }}\build
          key: windows-build
          restore-keys: windows-build

      - name: (8) Build
        working-directory: ${{ runner.temp }}\build
        env:
          GMP_INCLUDE_DIRS: "C:/Program Files (x86)/GMP/include"
          GMP_LIBRARIES: "C:/Program Files (x86)/GMP/lib"
          GMP_WINDOWS_PATH: "C:/Program Files (x86)/GMP"
          CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}
        run:  |
              cmake -S ${{github.workspace}} -B . -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Release>:Release>"
              cmake --build . --parallel 8 --config Release -- /p:Platform=x64 /p:NODEFAULTLIB=msvcprt.lib /p:RuntimeLibrary=MT_StaticRelease

      - name: (9) Zip build
        working-directory: ${{ runner.temp }}
        run:  |
              7z a qt-planets-build.zip "C:/Program Files (x86)/*" -r
              
      - name: (10) Save build artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}\${{ env.ARTIFACT }}
