name: Windows Release

on:
  push:
    branches:
      - 'main'

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   5.15.2
  ARTIFACT:     qt-planets-build.zip
  INSTALL_DIRECTORY: "D:/install"

jobs:
  build:
    runs-on:  ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest, windows-2019]

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}
        run: |
          git fetch --all --tags -f

      - name: (3) Install Qt
        uses: jurplel/install-qt-action@v2
        if:  matrix.os == 'windows-2019'
        with:
          version:      ${{ env.QT_VERSION }}
          host:         windows
          target:       desktop
          arch:         win64_msvc2019_64
          dir:          ${{ runner.temp }}
          modules:      qtcharts qt3d
          setup-python: false
        if:  matrix.os == 'ubuntu-latest'
        with:
          version:      ${{ env.QT_VERSION }}
          host:         linux
          target:       desktop
          arch:         gcc_64
          dir:          ${{ runner.temp }}
          modules:      qtcharts qt3d
          setup-python: false

      - name: Create build directory
        run:  mkdir ${{ runner.temp }}\build

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Cache Build
        uses: actions/cache@v3
        with: 
          path: ${{ runner.temp }}\build
          key: ${{ matrix.os }}-build
          restore-keys: ${{ matrix.os }}-build

      - name: Build
        working-directory: ${{ runner.temp }}\build
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}
        run:  |
              cmake -S ${{github.workspace}} -B . -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIRECTORY }} -Wno-dev
              cmake --build . --parallel 8 --config Release -- /p:Platform=x64 /p:NODEFAULTLIB=msvcprt.lib
      - name: Zip build
        working-directory: ${{ runner.temp }}
        run:  |
              7z a ${{ env.ARTIFACT }} ${{ env.INSTALL_DIRECTORY }}/* -r

      - name: Save build artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}\${{ env.ARTIFACT }} 
