name: Windows Release

on:
  push:
    branches:
      - 'main'

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   5.15.2
  ARTIFACT:     qt-planets-build.zip
  INSTALL_DIRECTORY: "D:/install"

jobs:
  build:
    runs-on:  windows-2019

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}
        run: |
          git fetch --all --tags -f
#      - name: (3) Install Qt
#        uses: jurplel/install-qt-action@v2
#        with:
#          version:      ${{ env.QT_VERSION }}
#          host:         windows
#          target:       desktop
#          arch:         win64_msvc2019_64
#          dir:          ${{ runner.temp }}
#          modules:      qtcharts qt3d
#          setup-python: false
              
      - name: Create build directory
        run:  mkdir ${{ runner.temp }}\build

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Cache Build
        uses: actions/cache@v3
        with: 
          path: ${{ runner.temp }}\build
          key: windows-build
          restore-keys: windows-build

      - name: Build
        working-directory: ${{ runner.temp }}\build
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}};${{ env.INSTALL_DIRECTORY }}/3rdparty/lib/cmake/gmp;${{ env.INSTALL_DIRECTORY }}/3rdparty/lib/cmake/gmpxx;${{ env.INSTALL_DIRECTORY }}/3rdparty/lib/cmake/spdlog;${{ env.INSTALL_DIRECTORY }}/3rdparty/lib/cmake/fmt
        run:  |
              cmake -S ${{github.workspace}} -B . -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Release>:Release>:DLL" -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIRECTORY }}
              cmake --build . --parallel 8 --config Release -- /p:Platform=x64 /p:NODEFAULTLIB=msvcprt.lib /p:RuntimeLibrary=MD_DynamicRelease
      - name: Zip build
        working-directory: ${{ runner.temp }}
        run:  |
              7z a ${{ env.ARTIFACT }} ${{ env.INSTALL_DIRECTORY }}/* -r
              
      - name: Save build artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}\${{ env.ARTIFACT }} 